GRANT ALL PRIVILEGES ON DATABASE taskmanager TO taskuser;
GRANT ALL ON SCHEMA public TO taskuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO taskuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO taskuser;
